// Default admin message templates used by frontend API fallback handlers.
export const DEFAULT_MOCK_MESSAGE_TEMPLATES = [
  {
    key: 'telegram_welcome',
    title: 'Приветствие Telegram',
    description: 'Что клиент получает в Telegram после команды /start.',
    body: '👋 <b>Привет, {{first_name}}!</b>\n\nДобро пожаловать в <b>ШАМРАЙ | ОШИБКИ БК</b>.\n\n📊 Прогнозы, ошибки БК и умные уведомления уже внутри приложения.\n\n{{contact_footer}}\n\n👇 Нажмите кнопку ниже, чтобы открыть Shamrai.',
    variables: [
      { key: 'first_name', label: 'Имя клиента', example: 'Алексей' },
      { key: 'contact_footer', label: 'Контактный блок', example: 'Если есть вопросы...' },
    ],
  },
  {
    key: 'announcement',
    title: 'Массовый анонс',
    description: 'Текст рассылки из раздела анонсов.',
    body: '{{emoji}} <b>{{title}}</b>\n\n{{body}}\n\n{{bookmaker_line}}\n{{match_link_line}}\n{{coefficient_line}}\n\n{{contact_footer}}',
    variables: [
      { key: 'emoji', label: 'Иконка типа анонса', example: '📢' },
      { key: 'title', label: 'Заголовок', example: 'Новый матч' },
      { key: 'body', label: 'Текст анонса', example: 'Есть новый анонс.' },
      { key: 'bookmaker_line', label: 'Строка БК', example: '🏦 БК: Фонбет' },
      { key: 'match_link_line', label: 'Строка ссылки', example: '🔗 Перейти к матчу' },
      { key: 'coefficient_line', label: 'Строка коэффициента', example: '📊 Коэффициент: 1.90' },
      { key: 'contact_footer', label: 'Контактный блок', example: 'Если есть вопросы...' },
    ],
  },
  {
    key: 'paid_set_teaser',
    title: 'Анонс платного набора',
    description: 'Сообщение клиенту: платный набор, коэффициент, стоимость и кнопка заявки.',
    body: '💰 <b>{{title}}</b> | КФ <b>{{coefficient}}</b>\n\n{{bookmaker_line}}\n\n{{body}}\n\nСтоимость: <b>{{price_text}}</b>\n\n{{contact_footer}}',
    variables: [
      { key: 'title', label: 'Название набора', example: 'Платный набор' },
      { key: 'coefficient', label: 'Коэффициент набора', example: '3.90' },
      { key: 'bookmaker_line', label: 'Строка БК', example: 'Фонбет | Пари | Bettery' },
      { key: 'body', label: 'Описание набора', example: 'Реальный КФ не выше 1.9!' },
      { key: 'price_text', label: 'Стоимость', example: '1 500 ₽' },
      { key: 'contact_footer', label: 'Контактный блок', example: 'Если есть вопросы...' },
    ],
  },
  {
    key: 'forecast_teaser',
    title: 'Закрытый анонс прогноза',
    description: 'Первое сообщение клиенту: взять или не взять закрытый прогноз.',
    body: '<b>Закрытый анонс прогноза</b>\n\nБК: {{bookmaker_labels}}\n\nКоэффициент: <b>{{coefficient}}</b>\n\n{{teaser_text}}\n\n{{contact_footer}}',
    variables: [
      { key: 'bookmaker_labels', label: 'Букмекеры', example: 'Фонбет, БетБум' },
      { key: 'coefficient', label: 'Коэффициент', example: '1.92' },
      { key: 'teaser_text', label: 'Короткий текст', example: 'Есть закрытый прогноз под вашу БК.' },
      { key: 'contact_footer', label: 'Контактный блок', example: 'Если есть вопросы...' },
    ],
  },
  {
    key: 'forecast_full',
    title: 'Полный прогноз',
    description: 'Сообщение с матчем, исходом, коэффициентом, описанием и купоном.',
    body: 'Матч: <b>{{event_name}}</b>\n\nИсход: <b>{{outcome}}</b>\n\nКоэффициент: <b>{{coefficient}}</b>\n\n{{bookmaker_line}}\n\n{{description}}\n\n{{bookmaker_links_block}}\n\n{{contact_footer}}',
    variables: [
      { key: 'event_name', label: 'Матч', example: 'Зенит - Спартак' },
      { key: 'outcome', label: 'Исход', example: 'П1' },
      { key: 'coefficient', label: 'Коэффициент', example: '1.92' },
      { key: 'bookmaker_line', label: 'Строка БК', example: 'БК: Фонбет' },
      { key: 'description', label: 'Описание', example: 'Короткая аналитика.' },
      { key: 'bookmaker_links_block', label: 'Блок ссылок', example: 'Фонбет: нажмите кнопку ниже' },
      { key: 'contact_footer', label: 'Контактный блок', example: 'Если есть вопросы...' },
    ],
  },
  {
    key: 'odds_drop',
    title: 'Падение коэффициента',
    description: 'Уведомление клиентам, которые уже взяли прогноз, что линия упала.',
    body: '🔥 <b>Посмотри, как выгодно взяли наш исход.</b>\n\nМатч: <b>{{event_name}}</b>\nИсход: <b>{{outcome}}</b>\n\nМы давали кф. <b>{{coefficient}}</b>, а сейчас линия уже упала до <b>{{odds_dropped_to}}</b>.\n\nПоздравляю с выгодной ставкой, ждём заход 🤝',
    variables: [
      { key: 'event_name', label: 'Матч', example: 'Зенит - Спартак' },
      { key: 'outcome', label: 'Исход', example: 'П1' },
      { key: 'coefficient', label: 'Коэффициент', example: '1.92' },
      { key: 'odds_dropped_to', label: 'Новый коэффициент', example: '1.64' },
    ],
  },
  {
    key: 'bet_win',
    title: 'Победа прогноза',
    description: 'Сообщение клиенту, когда взятый прогноз рассчитан плюсом.',
    body: '🔥 Прогноз Shamrai рассчитан в плюс!\n\nМатч «{{event_name}}» успешно закрыт победой. 🧠 Списание купона произведено честно, ваш банк увеличен. Работаем дальше.🤝',
    variables: [{ key: 'event_name', label: 'Матч', example: 'Зенит - Спартак' }],
  },
  {
    key: 'bet_loss',
    title: 'Неудача прогноза',
    description: 'Обычное сообщение о минусе, если компенсация клиенту не начисляется.',
    body: 'Прогноз «{{event_name}}» закрыт минусом.\n\nДержим дистанцию и работаем дальше.',
    variables: [{ key: 'event_name', label: 'Матч', example: 'Зенит - Спартак' }],
  },
  {
    key: 'bet_loss_supercompensation',
    title: 'Неудача с компенсацией',
    description: 'Сообщение о минусе, когда клиенту возвращается ставка и добавляется бонус.',
    body: '⚡ Сверхкомпенсация Shamrai активирована.\n\nПрогноз «{{event_name}}» закрыт минусом, поэтому мы вернули списанную ставку и начислили +1 бонусную ставку сверху. Баланс абонемента увеличен на 2.',
    variables: [{ key: 'event_name', label: 'Матч', example: 'Зенит - Спартак' }],
  },
  {
    key: 'bet_refund',
    title: 'Возврат прогноза',
    description: 'Сообщение клиенту, когда прогноз рассчитан возвратом.',
    body: '↩️ Прогноз «{{event_name}}» рассчитан возвратом.\n\nСтавка возвращается по правилам БК.',
    variables: [{ key: 'event_name', label: 'Матч', example: 'Зенит - Спартак' }],
  },
  {
    key: 'live_signal',
    title: 'Live-сигнал',
    description: 'Срочное уведомление по live-прогнозу.',
    body: '⚡⚡⚡ SHAMRAI LIVE SIGNAL ALARM ⚡⚡⚡\n\nНовый срочный Live-прогноз от Shamrai:\n🏆 {{event_name}}\n📈 Коэффициент: {{coefficient}}\n{{brain_score_line}}\n\nБыстрее заходите в приложение Shamrai Analytics Hub!',
    variables: [
      { key: 'event_name', label: 'Матч', example: 'Зенит - Спартак' },
      { key: 'coefficient', label: 'Коэффициент', example: '1.92' },
      { key: 'brain_score_line', label: 'Строка Brain Score', example: '🧠 Brain Score: 8/10' },
    ],
  },
];
